#!/usr/bin/env python3
"""Generate EnglishHeteronyms.swift from Misaki's us_gold.json.

Keeps entries with >= 2 distinct non-null pronunciations, restricted to the
POS buckets an NLTagger lexical-class pass can distinguish (DEFAULT / VERB /
NOUN / ADJ / ADV). Tense-specific Penn keys (VBD/VBN/VBP) are dropped: the
runtime tagger can't tell tense apart, so those words keep their DEFAULT
reading, matching the pre-heteronym behavior.

Usage: generate_english_heteronyms.py <us_gold.json> <output.swift>
"""

import json
import sys

KEPT_TAGS = {"DEFAULT", "VERB", "NOUN", "ADJ", "ADV"}


def main() -> None:
    gold_path, out_path = sys.argv[1], sys.argv[2]
    gold = json.load(open(gold_path, encoding="utf-8"))

    table: dict[str, dict[str, str]] = {}
    for word, entry in gold.items():
        if not isinstance(entry, dict):
            continue
        kept = {
            tag: ipa
            for tag, ipa in entry.items()
            if tag in KEPT_TAGS and ipa is not None
        }
        if "DEFAULT" not in kept or len(set(kept.values())) < 2:
            continue
        key = word.lower()
        # Lower-case spellings win over capitalized variants of the same word.
        if key in table and word != key:
            continue
        table[key] = kept

    lines = [
        "// Generated by scripts/generate_english_heteronyms.py from Misaki us_gold.json.",
        "// Do not edit by hand.",
        "",
        "/// Words whose pronunciation depends on part of speech, keyed",
        "/// lower-cased word -> coarse POS tag (DEFAULT/VERB/NOUN/ADJ/ADV) -> Misaki IPA.",
        "enum EnglishHeteronyms {",
        "    static let table: [String: [String: String]] = [",
    ]
    for word in sorted(table):
        tags = table[word]
        pairs = ", ".join(
            f'"{tag}": "{tags[tag]}"' for tag in sorted(tags)
        )
        lines.append(f'        "{word}": [{pairs}],')
    lines.append("    ]")
    lines.append("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(table)} heteronyms -> {out_path}")


if __name__ == "__main__":
    main()
